### ISSUE TITLE
crashing because `app.trees.app` is not a string in ember-cli 1.13.13

### ISSUE THREAD

**Issue by kushdilip** [sivakumar-kailasam/broccoli-leasot#55]
I am using `Ember 1.13.11` & `Ember-cli 1.13.13`. The build fails at https://github.com/sivakumar-kailasam/broccoli-leasot/blob/master/ember-addon-main.js#L15.

the console.log for `app.trees` looks like

```
{ app: 
   { _directoryPath: 'app',
     _watched: true,
     _name: 'WatchedDir',
     _annotation: undefined,
     _instantiationStack: '
...
```

and probably `var pathToApp = path.resolve(app.project.root, app.trees.app);` expects `app.trees.app` to be string, and below error is thrown 

```
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at Class.module.exports.included ([FULL_PATH]/node_modules/broccoli-leasot/ember-addon-main.js:15:24)
```

How this crash can be handled?

**Comment by sivakumar-kailasam** [comment]
I've noticed this one and been meaning to fix this. Will try to post the possible fix on this issue and solve it.

**Comment by sivakumar-kailasam** [comment]
@kushdilip figured out the root cause. it's because one of the ember-cli's internal data model had changed over time. I'm fixing it in a way that its backward compatible in a patch release. Will release a major version shortly that supports addons as well.
